version: "3.9"
services:
    db:
        container_name: dataprovider-db
        image: postgres:16
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=
            - POSTGRES_DB=djangoapp
        volumes:
            - postgres_data:/var/lib/postgres/data/
        ports:
            - "5432:5432"
        restart: unless-stopped

    backend:
        build:
            context: ./
            dockerfile: ./customBackend/DockerFile
        container_name: dataprovider-backend
        image: dataprovider-backend
        ports:
            - "8080:8080"
        depends_on:
            - db

    frontend:
        build:
            context: ./
            dockerfile: ./vue-frontend/DockerFile
        container_name: dataprovider-frontend
        image: dataprovider-frontend
        command: bash -c "docker run --rm -p 8081:8081 -e "HOST=0.0.0.0" -d dataprovider-frontend"
        ports:
            - "8081:8081"
        depends_on:
            - backend

volumes:
    postgres_data: