# Generated by Django 4.2.7 on 2023-12-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProvider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.CharField(default='099'),
        ),
    ]
