# Generated by Django 4.2.7 on 2023-12-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProvider', '0002_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.CharField(),
        ),
    ]
