# Generated by Django 4.2.7 on 2023-12-03 07:57

import dataProvider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProvider', '0004_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='stats',
            field=models.JSONField(default=dataProvider.models.default_performance),
        ),
    ]
