# Generated by Django 4.2.7 on 2023-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataProvider', '0005_alter_performance_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='stats',
            field=models.JSONField(),
        ),
    ]
